export interface FlagType {
  AbilitiesOnBothPages: string
  AdjustPositionOnTerrainCollision: string
  AllowAutoGarrison: string
  AllowPlacementOnIce: string
  AlwaysAllowOverPopCap: string
  AlwaysFullColorAsCursor: string
  AnnounceConversion: string
  AnnounceDestruction: string
  AnnounceFoundationStarted: string
  AreaDamageConstant: string
  AutoCommandStartDisabled: string
  AutoTrainable: string
  BallisticTrackSource: string
  BattleMusicTrigger: string
  CanAutoHeal: string
  CanTargetButTakesNoDamage: string
  CannotAttackDisabledUnits: string
  CannotAttackIfNature: string
  CannotSnare: string
  CollidesWithProjectiles: string
  ColorTransformNonNature: string
  CommonCommands: string
  ConstrainOrientation: string
  ConvertOnStartBuild: string
  ConvertToNatureAtZeroHitpoints: string
  ConvertToTOB: string
  CorpseDecays: string
  CreateUnitGroupAutomatically: string
  DecalStickToWaterSurface: string
  DeleteConfirmation: string
  DependentAttack: string
  DependentKeepAlive: string
  DestroyUnderBuilding: string
  DieAtZeroResources: string
  DirectProjectile: string
  DisplayBuildingProgress: string
  DisplayMinimumRange: string
  DisplayRange: string
  DisplayRangeOverride: string
  DisplayUpgradeProgress: string
  DoNotAllowAlliedGarrison: string
  DoNotDieAtZeroHitpoints: string
  DoNotDragSelectWithUnits: string
  DoNotShowOnMiniMap: string
  DoNotValidateResourceInventory: string
  DoNotYawDuringMovement: string
  DontMarkExtraFog: string
  DontRotateObstruction: string
  DoppleOnlyWhenDead: string
  Doppled: string
  DynamicUpdate: string
  DynamicUpdateAnimate: string
  EnterHotkeyContext: string
  ExcludeFromIdleQuery: string
  ExcludeFromMoveAllMilitary: string
  ExperienceUnit: string
  FadeOutDecalOnDeath: string
  FadeOutDuringDeathAnimation: string
  FlareOnFullyBuilt: string
  FlattenGround: string
  FlyingUnit: string
  ForceBuildingData: string
  ForceEmpowerable: string
  ForceNormalDeathAnim: string
  ForceSecondPage: string
  ForceSquareSelection: string
  ForceToNature: string
  GivesLOSToAll: string
  GodPowerExclusion: string
  GroupSelection: string
  HasContinuousParticles: string
  HasDefaultAttack: string
  HasGatherPoint: string
  HeroNamePharaoh: string
  HeroNameSimple: string
  HideCostFromDetailHelp: string
  HideFromDialogs: string
  HideGarrisonCapacity: string
  HideGarrisonFlag: string
  HideHitpointsIfNature: string
  HideResourceInventory: string
  HideStances: string
  Immoveable: string
  InitialGarrisonOnly: string
  Invulnerable: string
  InvulnerableIfNature: string
  InvulnerableOnBirth: string
  KillOnAnimLoop: string
  KillsTargetAfterPickupAction: string
  KnockoutDeath: string
  LifespanBirth: string
  MagnetDoesNotLockUnits: string
  MilitaryCommands: string
  MinimapDisplayOnTop: string
  NeverCountDeathAsLoss: string
  NoHPBar: string
  NoIdleActions: string
  NoLockedAnimationOnDeath: string
  NoTieToGround: string
  NoUnitAI: string
  NonAutoFormedUnit: string
  NonCollideable: string
  NonSolid: string
  NotAlive: string
  NotAttackableByNature: string
  NotCommandable: string
  NotDeathTracked: string
  NotDeleteable: string
  NotDeleteableFoundation: string
  NotEjectable: string
  NotKBTracked: string
  NotManuallyPlaceable: string
  NotObscuredByUnitsAsFoundation: string
  NotPlayerPlaceable: string
  NotPushable: string
  NotRepairable: string
  NotSearchable: string
  NotSelectable: string
  ObscuredByUnits: string
  ObscuresUnits: string
  OnlyInEditor: string
  OrientUnitWithGround: string
  OrientUnitWithGroundRoll: string
  PaintTextureWhenPlacing: string
  Pickable: string
  PlaceAnywhere: string
  PlaceAsFoundation: string
  PlaceSocketWhenPlacing: string
  PlaySoundOnConversion: string
  PlayerOwnsObstruction: string
  PrayableTo: string
  PreventsWallBuilding: string
  Projectile: string
  ProjectileTerrainOnly: string
  PushPlacement: string
  RMCanRotate: string
  RangeIndicatorForAbilityCasting: string
  RecoverableDeathHeal: string
  Relic: string
  RevealFoundation: string
  RevertToSocketAtZeroHitpoints: string
  RotateInPlace: string
  SelectWithObstruction: string
  SharedGarrison: string
  ShowGarrisonButton: string
  ShowUntouchedFoundation: string
  SkipFlyingDeathAnim: string
  SnapPlacement: string
  SolidFoundation: string
  SplitQueue: string
  StartOnAnimationUpdate: string
  StartOnNoUpdate: string
  TieToWaterSurface: string
  TileAlignPlacement: string
  UnitTransformFree: string
  UnlimitedSupply: string
  UpgradeSocket: string
  UseAlignedObstructionOnMinimap: string
  UseAltEmpowerCursor: string
  UseFarmingAnims: string
  UseSharedBuildLimit: string
  VariationLocked: string
  VisibleOwnerOnly: string
  VisibleUnderFog: string
  VisibleUnderFogIfNature: string
  VisibleUnderFogOnlyAfterSeen: string
  Wanders: string
  wallBuild: string
}

export interface UnitType {
  AbstractArcher: string
  AbstractArcherShip: string
  AbstractArmory: string
  AbstractCavalry: string
  AbstractCloseCombatShip: string
  AbstractDock: string
  AbstractDwarf: string
  AbstractEmpowerer: string
  AbstractFarm: string
  AbstractFishingShip: string
  AbstractFlyingUnit: string
  AbstractFortress: string
  AbstractGullinbursti: string
  AbstractHealer: string
  AbstractHouseBuildLimit: string
  AbstractInfantry: string
  AbstractInvisibleWall: string
  AbstractMarket: string
  AbstractMonument: string
  AbstractOracle: string
  AbstractPharaoh: string
  AbstractScout: string
  AbstractSettlement: string
  AbstractSiegeShip: string
  AbstractSiegeWeapon: string
  AbstractSocketedTownCenter: string
  AbstractTemple: string
  AbstractTitan: string
  AbstractTower: string
  AbstractTownCenter: string
  AbstractTransportShip: string
  AbstractVillager: string
  AbstractWalkingWoods: string
  AbstractWall: string
  AbstractWarship: string
  AbstractWarshipHero: string
  AbstractWonder: string
  AffectedByTownBell: string
  AnimalOfSet: string
  AnimalPredator: string
  AnimalPrey: string
  AnimalReactive: string
  ArcherLineUpgraded: string
  AsgardianHillFort: string
  Brokk: string
  BuildLimitSharedAtlantean: string
  BuildLimitSharedNorse: string
  Building: string
  BuildingClass: string
  CavalryLineUpgraded: string
  CountsTowardEconomicScore: string
  CountsTowardMilitaryScore: string
  DisplayQueue: string
  Dropsite: string
  EconomicUnit: string
  EconomicUpgraded: string
  Eitri: string
  EmbellishmentClass: string
  FishResource: string
  FoodDropsite: string
  GoldDropsite: string
  GoldResource: string
  Herdable: string
  HerdableMagnet: string
  Hero: string
  HeroOfRagnarok: string
  HeroOfRagnarokDwarf: string
  HeroShadowUpgraded: string
  HesperidesTree: string
  HillFort: string
  HumanSoldier: string
  Huntable: string
  HuntedResource: string
  InfantryLineUpgraded: string
  LogicalTypeAffectedByCeaseFireBuildingSlow: string
  LogicalTypeAffectedByRestoration: string
  LogicalTypeAffectedByValleyOfTheKings: string
  LogicalTypeAffectedByValor: string
  LogicalTypeAgeUpBuilding: string
  LogicalTypeAgressiveNatureUnit: string
  LogicalTypeArchaicMythUnit: string
  LogicalTypeAutoAttackFocusBuildings: string
  LogicalTypeBuildingEmpoweredForLOS: string
  LogicalTypeBuildingNotWonderOrTitan: string
  LogicalTypeBuildingThatCanBeEmpowered: string
  LogicalTypeBuildingsNotWalls: string
  LogicalTypeBuildingsThatShoot: string
  LogicalTypeClassicalMythUnit: string
  LogicalTypeConvertsHerds: string
  LogicalTypeEarthquakeAttack: string
  LogicalTypeEasySelectAvoid: string
  LogicalTypeFindBarracks: string
  LogicalTypeFindFoodDropsite: string
  LogicalTypeFindGoldDropsite: string
  LogicalTypeFindStable: string
  LogicalTypeFindWoodDropsite: string
  LogicalTypeFreezableMythUnit: string
  LogicalTypeGarrisonInShips: string
  LogicalTypeHandUnitsAttack: string
  LogicalTypeHandUnitsAutoAttack: string
  LogicalTypeHealed: string
  LogicalTypeHeroicMythUnit: string
  LogicalTypeLandMilitary: string
  LogicalTypeMilitaryProductionBuilding: string
  LogicalTypeMinimapFilterEconomic: string
  LogicalTypeMinimapFilterMilitary: string
  LogicalTypeMythUnitNotFlying: string
  LogicalTypeMythUnitNotTitan: string
  LogicalTypeMythUnitThatGeneratesFavor: string
  LogicalTypeMythicMythUnit: string
  LogicalTypeNavalMilitary: string
  LogicalTypeNeededForVictory: string
  LogicalTypeNorseSoldierThatBuilds: string
  LogicalTypeParticipatesInBattlecries: string
  LogicalTypePickable: string
  LogicalTypeRangedMythUnit: string
  LogicalTypeRangedUnitsAttack: string
  LogicalTypeRangedUnitsAutoAttack: string
  LogicalTypeSeidrTarget: string
  LogicalTypeSharedHeroSelection: string
  LogicalTypeShipNotHero: string
  LogicalTypeSunRayProjectile: string
  LogicalTypeTCBuildLimit: string
  LogicalTypeTartarianGateValidOverlapPlacement: string
  LogicalTypeTeleporterBuilding: string
  LogicalTypeUnitIsConstructed: string
  LogicalTypeValidBoltTarget: string
  LogicalTypeValidFrostTarget: string
  LogicalTypeValidLocustSwarmTarget: string
  LogicalTypeValidMeteorTarget: string
  LogicalTypeValidSPCUnitsDeadCondition: string
  LogicalTypeValidSentinelTarget: string
  LogicalTypeValidShiftingSandsTarget: string
  LogicalTypeValidShockwaveTarget: string
  LogicalTypeValidSpyTarget: string
  LogicalTypeValidTornadoAttack: string
  LogicalTypeValidTraitorTarget: string
  LogicalTypeVillagerNotHero: string
  LogicalTypeVillagersAttack: string
  LogicalTypeVillagersAttackResponse: string
  LogicalTypeVillagersRespondToAttack: string
  MajorHero: string
  MilitaryBuilding: string
  MilitaryUnit: string
  Minion: string
  MinionReincarnated: string
  MinorHero: string
  MythUnit: string
  MythUnitCavalry: string
  MythUnitMelee: string
  MythUnitRanged: string
  MythUnitSiege: string
  Nature: string
  NatureClass: string
  NavalUnit: string
  NonConvertableHerdable: string
  Pegasus: string
  PegasusBridleOfPegasus: string
  PegasusWingedMessenger: string
  Phoenix: string
  PhoenixFromEgg: string
  Projectile: string
  Ranged: string
  Resource: string
  Ship: string
  Socket: string
  SummoningTree: string
  TownCenter: string
  TradeUnit: string
  TradeableFrom: string
  TradeableTo: string
  Transport: string
  Tree: string
  Unattackable: string
  Unit: string
  UnitClass: string
  ValidIdleVillager: string
  VillageCenter: string
  VillagerHero: string
  WildCrops: string
  WoodDropsite: string
}

export interface TechType {
  AdzeOfWepwawet: string
  AegisShield: string
  AlluvialClay: string
  Ambassadors: string
  Anastrophe: string
  Architects: string
  ArcticWinds: string
  ArgivePatronage: string
  Argonauts: string
  AsbestosShields: string
  AsperBlood: string
  AtefCrown: string
  AvengingSpirit: string
  AxeOfVengeance: string
  BallistaTower: string
  Ballistics: string
  BeastSlayer: string
  Berserkergang: string
  BiteOfTheShark: string
  BoilingOil: string
  BoneBow: string
  BookOfThoth: string
  BowSaw: string
  Bravery: string
  BronzeArmor: string
  BronzeShields: string
  BronzeWall: string
  BronzeWeapons: string
  BurningPitch: string
  CallOfValhalla: string
  Carpenters: string
  CarrierPigeons: string
  CaveTroll: string
  Celerity: string
  ChampionArchers: string
  ChampionAxemen: string
  ChampionCamelRiders: string
  ChampionCavalry: string
  ChampionChariotArchers: string
  ChampionInfantry: string
  ChampionSlingers: string
  ChampionSpearmen: string
  ChampionWarElephants: string
  ChampionWarships: string
  Channels: string
  ChthonicRites: string
  CitadelWall: string
  Clairvoyance: string
  ClassicalAgeAnubis: string
  ClassicalAgeAres: string
  ClassicalAgeAthena: string
  ClassicalAgeBast: string
  ClassicalAgeForseti: string
  ClassicalAgeFreyja: string
  ClassicalAgeHeimdall: string
  ClassicalAgeHermes: string
  ClassicalAgeLeto: string
  ClassicalAgeOceanus: string
  ClassicalAgePrometheus: string
  ClassicalAgePtah: string
  ClassicalAgeUllr: string
  Coinage: string
  ConscriptBarracksSoldiers: string
  ConscriptCavalry: string
  ConscriptCounterSoldiers: string
  ConscriptGreatHallSoldiers: string
  ConscriptHillFortSoldiers: string
  ConscriptInfantry: string
  ConscriptLonghouseSoldiers: string
  ConscriptMainlineSoldiers: string
  ConscriptMigdolSoldiers: string
  ConscriptPalaceSoldiers: string
  ConscriptRangedSoldiers: string
  ConscriptSailors: string
  CopperArmor: string
  CopperShields: string
  CopperWeapons: string
  Crenellations: string
  CrimsonLinen: string
  Criosphinx: string
  Crocodilopolis: string
  Daktyloi: string
  DarkWater: string
  DaughtersOfTheSea: string
  DeimosSwordOfDread: string
  DesertWind: string
  DevoteesOfAtlas: string
  Dionysia: string
  Disablot: string
  DivineBlood: string
  DraftHorses: string
  DragonscaleShields: string
  DwarvenAuger: string
  DwarvenBreastplate: string
  DwarvenWeapons: string
  ElectrumBullets: string
  EmpyreanSpeed: string
  EnclosedDeck: string
  Engineers: string
  EnyosBowOfHorror: string
  EyesInTheForest: string
  FaceOfTheGorgon: string
  FeastsOfRenown: string
  FeetOfTheJackal: string
  FlamesOfTyphon: string
  FloodControl: string
  FloodOfTheNile: string
  ForceOfTheWestWind: string
  ForgeOfOlympus: string
  FortifiedTownCenter: string
  FortifiedWall: string
  FreyrsGift: string
  FrontlineHeroics: string
  FuneralBarge: string
  FuneralRites: string
  FuryOfTheFallen: string
  Gemini: string
  GiantSlayingBlades: string
  Gjallarhorn: string
  GoldenApples: string
  GraniteBlood: string
  GraniteMaw: string
  GraspOfRan: string
  GreatestOfFifty: string
  GuardTower: string
  GuardianOfIo: string
  HallOfThanes: string
  HaloOfTheSun: string
  Hamask: string
  HammerOfThunder: string
  HandAxe: string
  HandOfTalos: string
  HandsOfThePharaoh: string
  HeartOfTheTitans: string
  HeavyArchers: string
  HeavyAxemen: string
  HeavyCamelRiders: string
  HeavyCavalry: string
  HeavyChariotArchers: string
  HeavyInfantry: string
  HeavySlingers: string
  HeavySpearmen: string
  HeavyWarElephants: string
  HeavyWarships: string
  HephaestusRevenge: string
  HeroicAgeAegir: string
  HeroicAgeAphrodite: string
  HeroicAgeApollo: string
  HeroicAgeBragi: string
  HeroicAgeDionysus: string
  HeroicAgeHyperion: string
  HeroicAgeNephthys: string
  HeroicAgeNjord: string
  HeroicAgeRheia: string
  HeroicAgeSekhmet: string
  HeroicAgeSkadi: string
  HeroicAgeSobek: string
  HeroicAgeTheia: string
  HeroicFleet: string
  HeroicRenewal: string
  Hieracosphinx: string
  HornsOfConsecration: string
  HuntingEquipment: string
  HuntressAxe: string
  Husbandry: string
  IronArmor: string
  IronShields: string
  IronWall: string
  IronWeapons: string
  Irrigation: string
  Jotuns: string
  LabyrinthOfMinos: string
  LanceOfStone: string
  LeatherFrameShield: string
  LevyBarracksSoldiers: string
  LevyCavalry: string
  LevyCounterSoldiers: string
  LevyGreatHallSoldiers: string
  LevyHillFortSoldiers: string
  LevyInfantry: string
  LevyLonghouseSoldiers: string
  LevyMainlineSoldiers: string
  LevyMigdolSoldiers: string
  LevyPalaceSoldiers: string
  LevyRangedSoldiers: string
  LongSerpent: string
  LordOfHorses: string
  Masons: string
  MediumArchers: string
  MediumAxemen: string
  MediumCavalry: string
  MediumInfantry: string
  MediumSlingers: string
  MediumSpearmen: string
  MeteoricIronArmor: string
  MonstrousRage: string
  MythicAgeArtemis: string
  MythicAgeAtlas: string
  MythicAgeBaldr: string
  MythicAgeHekate: string
  MythicAgeHel: string
  MythicAgeHelios: string
  MythicAgeHephaestus: string
  MythicAgeHera: string
  MythicAgeHorus: string
  MythicAgeOsiris: string
  MythicAgeThoth: string
  MythicAgeTyr: string
  MythicAgeVidar: string
  MythicRejuvenation: string
  Nebty: string
  Necropolis: string
  NewKingdom: string
  NineWaves: string
  OlympianParentage: string
  OlympianWeapons: string
  Omniscience: string
  Oracle: string
  OrichalcumMail: string
  OrichalcumWall: string
  OsmiumArmor: string
  Perception: string
  Petrification: string
  PhobosSpearOfPanic: string
  Pickaxe: string
  PioneerOfTheSkies: string
  Plow: string
  PoseidonsSecret: string
  PropheticSight: string
  PurseSeine: string
  Quarry: string
  Rampage: string
  RheiasGift: string
  Rigsthula: string
  Rime: string
  RingGiver: string
  RingOath: string
  RoarOfOrthus: string
  SacredCats: string
  Safeguard: string
  SaltAmphora: string
  Sarissa: string
  ScallopedAxe: string
  SecretsOfTheTitans: string
  SerpentSpear: string
  ServantsOfGlory: string
  Sessrumnir: string
  Shaduf: string
  ShaftMine: string
  ShaftsOfPlague: string
  ShoulderOfTalos: string
  SignalFires: string
  SilentResolve: string
  SkinOfTheRhino: string
  SlingsOfTheSun: string
  SolarBarque: string
  SonsOfSleipnir: string
  SonsOfTheSun: string
  SpearOfHorus: string
  SpiritOfMaat: string
  SpiritedCharge: string
  StoneWall: string
  SunRay: string
  SundriedMudBrick: string
  SwineArray: string
  SylvanLore: string
  TaxCollectors: string
  TempleOfHealing: string
  TemporalChaos: string
  TheftOfFire: string
  ThracianHorses: string
  ThunderingHooves: string
  ThurisazRune: string
  TitanShield: string
  Titanomachy: string
  TusksOfApedemak: string
  TwilightOfTheGods: string
  Valgaldr: string
  ValleyOfTheKings: string
  VaultsOfErebus: string
  Vikings: string
  VolcanicForge: string
  WatchTower: string
  WeightlessMace: string
  WillOfKronos: string
  WingedMessenger: string
  WinterHarvest: string
  WrathOfTheDeep: string
  Ydalir: string
}

export interface SharedSelectionUnitTypes {
  AbstractMonument: string
  AbstractWalkingWoods: string
  AsgardianHillFort: string
  Brokk: string
  BuildLimitSharedAtlantean: string
  Eitri: string
  HeroOfRagnarok: string
  HeroOfRagnarokDwarf: string
  HillFort: string
  LogicalTypeSharedHeroSelection: string
  Minion: string
  MinionReincarnated: string
  Pegasus: string
  PegasusBridleOfPegasus: string
  PegasusWingedMessenger: string
  Phoenix: string
  PhoenixFromEgg: string
  TownCenter: string
  VillageCenter: string
}

export type ResourceType = "Favor" | "Food" | "Gold" | "Wood"
export type MovementType = "amphibious" | "land" | "water" | "air"
export interface Unit {
  name: string
  displaynameid: string
  animfile: string
  obstructionradiusx: number
  obstructionradiusz: number
  lifespan: number
  decay: {
    delay: number
    duration: number
  }
  movementtype: string
  maxvelocity: number
  los: number
  unittype: UnitType[]
  flag: FlagType[]
  spawn: {
    type: string
    count: number
  }
  projectilespinperiod: number
  soundsetfile: string
  unitaitype: string
  tactics: string
  protoaction: {
    name: string
    modifytype: string
    modifyamount: number
    modifyratecap: number
    modifybase: number
    modifydecay: number
  }
  selfdestructprotoaction: string
  rollovertextid: string
  shortrollovertextid: string
  editornameid: string
  icon: string
  impacttype: string
  turnrate: number
  initialhitpoints: number
  maxhitpoints: number
  trainpoints: number
  buildlimit: number
  weightclass: number
  populationcount: number
  carrycapacity: {
    resourcetype: ResourceType
  }
  hotkeycontext: string
  train: {
    row: number
    column: number
  }
  command: {
    row: number
    column: number
  }
  selectionradiusx: number
  selectionradiusz: number
  autoattackrange: number
  formationorder: number
  maxcontained: number
  contain: string
  notcontain: string
  sharedselectionunittypes: {
    unittype: SharedSelectionUnitTypes
  }
  rechargetime: number
  buildpoints: number
  culture: string
  maxrunvelocity: number
  veterancyranks: {}
  veterancybonus: {}
  minimapicon: string
  sizeclass: number
  unitregen: number
  heighthitpointbaroffset: number
  initialresource: {
    resourcetype: ResourceType
  }
  resourcesubtype: string
  resourcedecay: number
  initialunitaistance: string
  aistancebasedistance: number
  wanderdistance: number
  sharedbuildlimitunit: string
  sharedbuildlimitunittypes: {
    unittype: string
  }
  transformcommand: string
  tech: TechType[]
  buildreplacement: string
  creationfadetime: {
    initalpha: number
  }
  birthprotoaction: string
  auxrechargetime: number
  displayedrange: number
  killreward: {
    resourcetype: string
  }
  dependentunit: string
  directionalarmor: {
    angle: number
    value: number
  }
  dynamicbuildlimitunittypes: {}
  screenshakeondestruction: number
  placementfile: string
  partisantype: string
  partisancount: number
  buildingworkrate: number
  populationcapaddition: number
  socketunittype: string
  nonsocketplaceprotoid: string
  allyhotkeycontext: string
  allowedheightvariance: number
  researchrate: number
  trainingrate: number
  ondiscoverlos: number
  farmingradiusx: number
  farmingradiusz: number
  farmingobstructionradiusx: number
  farmingobstructionradiusz: number
  farmingnumstops: number
  gathererlimit: number
  minimapcolor: {
    red: number
    blue: number
    green: number
  }
  autobuildrate: number
  resourcepriority: number
  workersoftlimit: number
  replacement: {
    type: string
  }
  gatherratemultiplier: number
  heightbob: {
    period: number
    magnitude: number
  }
  containedhitpointbonus: number
  containedspeedbonus: number
}

export interface UnitDone {
  animfile: string
  obstructionradiusx: number
  obstructionradiusz: number
  lifespan: number
  decay: {
    delay: number
    duration: number
  }
  los: number
  spawn: {
    type: string
    count: number
  }
  projectilespinperiod: number
  soundsetfile: string
  unitaitype: string
  tactics: string
  protoaction: {
    name: string
    modifytype: string
    modifyamount: number
    modifyratecap: number
    modifybase: number
    modifydecay: number
  }
  selfdestructprotoaction: string
  rollovertextid: string
  shortrollovertextid: string
  icon: string
  impacttype: string
  initialhitpoints: number
  maxhitpoints: number
  trainpoints: number
  buildlimit: number
  weightclass: number
  populationcount: number
  carrycapacity: {
    resourcetype: ResourceType
  }
  hotkeycontext: string
  train: {
    row: number
    column: number
  }
  command: {
    row: number
    column: number
  }
  selectionradiusx: number
  selectionradiusz: number
  autoattackrange: number
  formationorder: number
  maxcontained: number
  contain: string
  notcontain: string
  sharedselectionunittypes: {
    unittype: SharedSelectionUnitTypes
  }
  rechargetime: number
  buildpoints: number
  culture: string
  maxrunvelocity: number
  veterancyranks: {}
  veterancybonus: {}
  minimapicon: string
  sizeclass: number
  unitregen: number
  heighthitpointbaroffset: number
  initialresource: {
    resourcetype: ResourceType
  }
  resourcesubtype: string
  resourcedecay: number
  initialunitaistance: string
  aistancebasedistance: number
  wanderdistance: number
  sharedbuildlimitunit: string
  sharedbuildlimitunittypes: {
    unittype: string
  }
  transformcommand: string
  tech: TechType[]
  buildreplacement: string
  creationfadetime: {
    initalpha: number
  }
  birthprotoaction: string
  auxrechargetime: number
  displayedrange: number
  killreward: {
    resourcetype: string
  }
  dependentunit: string
  directionalarmor: {
    angle: number
    value: number
  }
  dynamicbuildlimitunittypes: {}
  screenshakeondestruction: number
  placementfile: string
  partisantype: string
  partisancount: number
  buildingworkrate: number
  populationcapaddition: number
  socketunittype: string
  nonsocketplaceprotoid: string
  allyhotkeycontext: string
  allowedheightvariance: number
  researchrate: number
  trainingrate: number
  ondiscoverlos: number
  farmingradiusx: number
  farmingradiusz: number
  farmingobstructionradiusx: number
  farmingobstructionradiusz: number
  farmingnumstops: number
  gathererlimit: number
  minimapcolor: {
    red: number
    blue: number
    green: number
  }
  autobuildrate: number
  resourcepriority: number
  workersoftlimit: number
  replacement: {
    type: string
  }
  gatherratemultiplier: number
  heightbob: {
    period: number
    magnitude: number
  }
  containedhitpointbonus: number
  containedspeedbonus: number
}
