export const categorizedPrototActions = ref<{ [key: string]: TagContentValue[] }>({
    'HandAttack': [
        protoActionsTags.damage,
        protoActionsTags.damagebonus,
        protoActionsTags.rof,
        protoActionsTags.maxrange,
        protoActionsTags.damagearea,
        protoActionsTags.onhiteffect,
        protoActionsTags.defaultattack,
        protoActionsTags.impacteffect,
        protoActionsTags.damageflags,
        protoActionsTags.active,
        protoActionsTags.selfdestruct,
        protoActionsTags.scalebycontainedunittype,
    ],
    'RangedAttack': [
        protoActionsTags.damage,
        protoActionsTags.rof,
        protoActionsTags.maxrange,
        protoActionsTags.damagebonus,
        protoActionsTags.projectile,
        protoActionsTags.numberprojectiles,
        protoActionsTags.volleymode,
        protoActionsTags.impacteffect,
        protoActionsTags.displayednumberprojectiles,
        protoActionsTags.minrange,
        protoActionsTags.trackrating,
        protoActionsTags.scalebycontainedunittype,
        protoActionsTags.defaultattack,
        protoActionsTags.onhiteffect,
        protoActionsTags.damagearea,
        protoActionsTags.damageflags,
        protoActionsTags.passthroughbuildings,
        protoActionsTags.maxheight,
        protoActionsTags.activeifcontainsunits,
        protoActionsTags.containscalebasedamage,
        protoActionsTags.attachvalidtargetonly,
        protoActionsTags.active,
        protoActionsTags.perfectaccuracy,
        protoActionsTags.homingballistics,
    ],
    'Pickup': [
        protoActionsTags.type,
        protoActionsTags.rate,
        protoActionsTags.maxrange,
        protoActionsTags.active,
    ],
    'DropOff': [
        protoActionsTags.type,
        protoActionsTags.rate,
        protoActionsTags.maxrange,
    ],
    'ChargedRangedAttack': [
        protoActionsTags.damagebonus,
        protoActionsTags.damage,
        protoActionsTags.rof,
        protoActionsTags.maxrange,
        protoActionsTags.projectile,
        protoActionsTags.numberprojectiles,
        protoActionsTags.damageflags,
        protoActionsTags.damagearea,
        protoActionsTags.volleymode,
        protoActionsTags.perfectaccuracy,
        protoActionsTags.impacteffect,
        protoActionsTags.maxheight,
        protoActionsTags.onhiteffect,
        protoActionsTags.passthroughbuildings,
        protoActionsTags.passthrough,
        protoActionsTags.instantballistics,
        protoActionsTags.targetground,
        protoActionsTags.throw,
        protoActionsTags.throwdistancemin,
        protoActionsTags.throwdistancemax,
        protoActionsTags.throwmaxheight,
        protoActionsTags.throwvelocity,
        protoActionsTags.areasortmode,
        protoActionsTags.maxsizeclass,
        protoActionsTags.maxspread,
        protoActionsTags.spreadfactor,
        protoActionsTags.launchpoint,
    ],
    'ChargedHandAttack': [
        protoActionsTags.onhiteffect,
        protoActionsTags.damage,
        protoActionsTags.rof,
        protoActionsTags.maxrange,
        protoActionsTags.damagebonus,
        protoActionsTags.damagearea,
        protoActionsTags.damageflags,
        protoActionsTags.throw,
        protoActionsTags.impactforcemin,
        protoActionsTags.impactforcemax,
        protoActionsTags.impactlaunchangle,
        protoActionsTags.areasortmode,
        protoActionsTags.impacteffect,
        protoActionsTags.rate,
        protoActionsTags.attachvalidtargetonly,
        protoActionsTags.displayednumberprojectiles,
        protoActionsTags.directionaldamagerefangle,
        protoActionsTags.maxsizeclass,
        protoActionsTags.workonfrozenunits,
    ],
    'Gore': [
        protoActionsTags.onhiteffect,
        protoActionsTags.rof,
        protoActionsTags.damage,
        protoActionsTags.maxrange,
        protoActionsTags.damageflags,
        protoActionsTags.maxsizeclass,
        protoActionsTags.damagearea,
        protoActionsTags.coneareaangle,
        protoActionsTags.outerdamageareadistance,
        protoActionsTags.outerdamageareafactor,
        protoActionsTags.fulldamagemaintarget,
        protoActionsTags.damagebonus,
        protoActionsTags.impacteffect,
    ],
    'Gather': [
        protoActionsTags.rate,
        protoActionsTags.dropsitegathering,
        protoActionsTags.maxrange,
    ],
    'Convert': [
        protoActionsTags.rate,
        protoActionsTags.minrate,
        protoActionsTags.conversionprotoid,
        protoActionsTags.maxrange,
    ],
    'Repair': [
        protoActionsTags.rate,
        protoActionsTags.maxrange,
        protoActionsTags.type,
        protoActionsTags.anim,
        protoActionsTags.typedmaxrange,
    ],
    'FlyingUnitAttack': [
        protoActionsTags.damage,
        protoActionsTags.damagebonus,
        protoActionsTags.rof,
        protoActionsTags.maxrange,
        protoActionsTags.projectile,
        protoActionsTags.displayednumberprojectiles,
        protoActionsTags.damagearea,
        protoActionsTags.damageflags,
        protoActionsTags.active,
    ],
    'SelfDestructAttack': [
        protoActionsTags.onhiteffect,
        protoActionsTags.damagebonus,
        protoActionsTags.damage,
        protoActionsTags.damagearea,
        protoActionsTags.damageflags,
        protoActionsTags.rate,
        protoActionsTags.type,
        protoActionsTags.attackaction,
        protoActionsTags.areasortmode,
        protoActionsTags.impacteffect,
        protoActionsTags.basedamagecap,
        protoActionsTags.allydamagemultiplier,
        protoActionsTags.maxsizeclass,
    ],
    'Build': [
        protoActionsTags.rate,
        protoActionsTags.maxrange,
        protoActionsTags.type,
        protoActionsTags.anim,
        protoActionsTags.typedmaxrange,
    ],
    'TitanAttack': [
        protoActionsTags.damagebonus,
        protoActionsTags.damage,
        protoActionsTags.rof,
        protoActionsTags.maxrange,
        protoActionsTags.damagearea,
        protoActionsTags.damageflags,
    ],
    'AntiWallAttack': [
        protoActionsTags.damage,
        protoActionsTags.rof,
        protoActionsTags.maxrange,
        protoActionsTags.damagearea,
        protoActionsTags.damageflags,
        protoActionsTags.projectile,
        protoActionsTags.minrange,
        protoActionsTags.numberprojectiles,
        protoActionsTags.impacteffect,
        protoActionsTags.scalebycontainedunittype,
        protoActionsTags.damagebonus,
    ],
    'AreaHeal': [
        protoActionsTags.maxrange,
        protoActionsTags.modifyamount,
        protoActionsTags.slowhealmultiplier,
        protoActionsTags.modifytargetlimit,
    ],
    'JumpAttack': [
        protoActionsTags.damagebonus,
        protoActionsTags.rof,
        protoActionsTags.damage,
        protoActionsTags.minrange,
        protoActionsTags.maxrange,
        protoActionsTags.damagearea,
        protoActionsTags.damageflags,
    ],
    'Heal': [
        protoActionsTags.type,
        protoActionsTags.rate,
        protoActionsTags.slowhealmultiplier,
        protoActionsTags.maxrange,
        protoActionsTags.donotignoredead,
    ],
    'BirthAttack': [
        protoActionsTags.damagebonus,
        protoActionsTags.onhiteffect,
        protoActionsTags.damage,
        protoActionsTags.type,
        protoActionsTags.attackaction,
        protoActionsTags.rate,
        protoActionsTags.damagearea,
        protoActionsTags.damageflags,
    ],
    'Hunting': [protoActionsTags.rate],
    'AutoGather': [
        protoActionsTags.rate,
        protoActionsTags.type,
        protoActionsTags.persistent,
        protoActionsTags.active,
    ],
    'PetrificationBonus': [
        protoActionsTags.active,
        protoActionsTags.type,
        protoActionsTags.persistent,
        protoActionsTags.modifytype,
        protoActionsTags.modifydamagetype,
        protoActionsTags.modifyamount,
        protoActionsTags.modifyratecap,
        protoActionsTags.modifybase,
        protoActionsTags.modifydecay,
    ],
    'Throw': [
        protoActionsTags.rof,
        protoActionsTags.damage,
        protoActionsTags.damagearea,
        protoActionsTags.damageflags,
        protoActionsTags.damagebonus,
        protoActionsTags.maxrange,
        protoActionsTags.workonfrozenunits,
        protoActionsTags.selfdestruct,
        protoActionsTags.rate,
        protoActionsTags.chargeaction,
    ],
    'DistanceLimiting': [
        protoActionsTags.type,
        protoActionsTags.persistent,
        protoActionsTags.modifytype,
        protoActionsTags.minrate,
        protoActionsTags.modifyamount,
        protoActionsTags.modifybase,
        protoActionsTags.minrange,
        protoActionsTags.maxrange,
    ],
    'AutoBoost': [
        protoActionsTags.onhiteffect,
        protoActionsTags.rof,
        protoActionsTags.maxrange,
        protoActionsTags.damageflags,
        protoActionsTags.rate,
        protoActionsTags.modelattachment,
        protoActionsTags.modelattachmentbone,
        protoActionsTags.damage,
        protoActionsTags.damagearea,
    ],
    'BuckAttack': [
        protoActionsTags.damage,
        protoActionsTags.rof,
        protoActionsTags.maxrange,
        protoActionsTags.workonfrozenunits,
        protoActionsTags.damagebonus,
        protoActionsTags.shockstun,
        protoActionsTags.stunduration,
        protoActionsTags.maxsizeclass,
    ],
    'LightningAttack': [
        protoActionsTags.rof,
        protoActionsTags.damage,
        protoActionsTags.damagebonus,
        protoActionsTags.maxrange,
        protoActionsTags.numberbounces,
        protoActionsTags.projectile,
    ],
    'FreezeAttack': [
        protoActionsTags.onhiteffect,
        protoActionsTags.rof,
        protoActionsTags.maxrange,
        protoActionsTags.projectile,
        protoActionsTags.workonfrozenunits,
    ],
    'BeamAttack': [
        protoActionsTags.damage,
        protoActionsTags.rof,
        protoActionsTags.maxrange,
        protoActionsTags.projectile,
        protoActionsTags.damagebonus,
        protoActionsTags.onhiteffect,
        protoActionsTags.attachprotounit,
        protoActionsTags.impacteffect,
        protoActionsTags.numberbounces,
        protoActionsTags.displayednumberprojectiles,
    ],
    'RangedAttackMyth': [
        protoActionsTags.rof,
        protoActionsTags.damage,
        protoActionsTags.damagebonus,
        protoActionsTags.maxrange,
        protoActionsTags.projectile,
    ],
    'Trade': [
        protoActionsTags.rate,
        protoActionsTags.minrate,
        protoActionsTags.maxrange,
    ],
    'ChargedSpawn': [
        protoActionsTags.active,
        protoActionsTags.type,
        protoActionsTags.rate,
        protoActionsTags.minrate,
        protoActionsTags.persistent,
        protoActionsTags.animationrate,
        protoActionsTags.chargeaction,
        protoActionsTags.forcespawn,
    ],
    'AreaDamage': [
        protoActionsTags.damagebonus,
        protoActionsTags.modifyamount,
        protoActionsTags.modifydamagetype,
        protoActionsTags.maxrange,
    ],
    'RangedAttackFlying': [
        protoActionsTags.rof,
        protoActionsTags.damage,
        protoActionsTags.damagebonus,
        protoActionsTags.maxrange,
        protoActionsTags.projectile,
    ],
    'AoEAttack': [
        protoActionsTags.damagebonus,
        protoActionsTags.rof,
        protoActionsTags.damage,
        protoActionsTags.damagearea,
        protoActionsTags.maxrange,
        protoActionsTags.damageflags,
    ],
    'ChopAttack': [
        protoActionsTags.damage,
        protoActionsTags.rof,
        protoActionsTags.rate,
    ],
    'TauntAttack': [
        protoActionsTags.onhiteffect,
        protoActionsTags.rof,
        protoActionsTags.damage,
        protoActionsTags.damagebonus,
        protoActionsTags.damagearea,
        protoActionsTags.damageflags,
        protoActionsTags.maxrange,
        protoActionsTags.forceareaattackcenter,
    ],
    'AutoConvert': [
        protoActionsTags.maxrange,
        protoActionsTags.includenature,
        protoActionsTags.cannotbeconvertedbyallies,
    ],
    'BuildingAttack': [
        protoActionsTags.damage,
        protoActionsTags.rof,
        protoActionsTags.maxrange,
        protoActionsTags.impacteffect,
        protoActionsTags.damagebonus,
        protoActionsTags.onhiteffect,
    ],
    'ReincarnationAttack': [
        protoActionsTags.onhiteffect,
        protoActionsTags.damagebonus,
        protoActionsTags.rof,
        protoActionsTags.damage,
        protoActionsTags.maxrange,
        protoActionsTags.projectile,
        protoActionsTags.damagearea,
        protoActionsTags.damageflags,
    ],
    'AutoLOS': [
        protoActionsTags.modifytype,
        protoActionsTags.modifyamount,
        protoActionsTags.modifyratecap,
        protoActionsTags.modifydecay,
    ],
    'FlameAttack': [
        protoActionsTags.damage,
        protoActionsTags.rof,
        protoActionsTags.damagebonus,
        protoActionsTags.maxrange,
        protoActionsTags.projectile,
        protoActionsTags.numberprojectiles,
        protoActionsTags.damagearea,
        protoActionsTags.damageflags,
        protoActionsTags.impacteffect,
    ],
    'DeathBoostDamageBonus': [
        protoActionsTags.type,
        protoActionsTags.modifyratebytype,
        protoActionsTags.modifyprotoid,
        protoActionsTags.active,
        protoActionsTags.maxrange,
        protoActionsTags.rate,
        protoActionsTags.persistent,
        protoActionsTags.modifytype,
        protoActionsTags.modifybase,
    ],
    'BlazingStrafeAttack': [
        protoActionsTags.damagebonus,
        protoActionsTags.rof,
        protoActionsTags.damage,
        protoActionsTags.minrate,
        protoActionsTags.modifyamount,
        protoActionsTags.maxrange,
        protoActionsTags.damagearea,
        protoActionsTags.damageflags,
    ],
    'ChannelAttack': [
        protoActionsTags.onhiteffect,
        protoActionsTags.rof,
        protoActionsTags.damage,
        protoActionsTags.damagebonus,
        protoActionsTags.maxrange,
        protoActionsTags.damagearea,
        protoActionsTags.damageflags,
    ],
    'AutoGatherFavor': [
        protoActionsTags.rate,
        protoActionsTags.modifybase,
        protoActionsTags.modifymultiplier,
        protoActionsTags.modifyratecap,
    ],
    'ShockwaveAttack': [
        protoActionsTags.damage,
        protoActionsTags.damagebonus,
        protoActionsTags.rof,
        protoActionsTags.maxrange,
        protoActionsTags.workonfrozenunits,
        protoActionsTags.maxsizeclass,
    ],
    'Capsize': [
        protoActionsTags.damagebonus,
        protoActionsTags.rof,
        protoActionsTags.damage,
        protoActionsTags.maxrange,
        protoActionsTags.damagearea,
        protoActionsTags.damageflags,
    ],
    'ProgressiveDamageLight': [
        protoActionsTags.damagebonus,
        protoActionsTags.modifyamount,
        protoActionsTags.modifydamagetype,
        protoActionsTags.maxrange,
        protoActionsTags.sendunderattackevent,
    ],
    'ProgressiveDamageHigh': [
        protoActionsTags.damagebonus,
        protoActionsTags.modifyamount,
        protoActionsTags.modifydamagetype,
        protoActionsTags.maxrange,
        protoActionsTags.sendunderattackevent,
    ],
    'IdleDamageBonus': [
        protoActionsTags.modifytype,
        protoActionsTags.modifyamount,
        protoActionsTags.modifyratecap,
        protoActionsTags.modifybase,
        protoActionsTags.modifydecay,
    ],
    'BillowingSmog': [
        protoActionsTags.damagebonus,
        protoActionsTags.modifyamount,
        protoActionsTags.modifydamagetype,
        protoActionsTags.maxrange,
    ],
    'Pacify': [
        protoActionsTags.onhiteffect,
        protoActionsTags.rof,
        protoActionsTags.maxrange,
        protoActionsTags.exclusive,
    ],
    'FreezeTitan': [
        protoActionsTags.rof,
        protoActionsTags.maxrange,
        protoActionsTags.projectile,
        protoActionsTags.onhiteffect,
        protoActionsTags.workonfrozenunits,
    ],
    'SpeedBonusMundane': [
        protoActionsTags.modifytype,
        protoActionsTags.modifyamount,
        protoActionsTags.modifyratecap,
        protoActionsTags.modifybase,
        protoActionsTags.modifydecay,
    ],
    'SpeedBonusRare': [
        protoActionsTags.modifytype,
        protoActionsTags.modifyamount,
        protoActionsTags.modifyratecap,
        protoActionsTags.modifybase,
        protoActionsTags.modifydecay,
    ],
    'SpeedBonusMythical': [
        protoActionsTags.modifytype,
        protoActionsTags.modifyamount,
        protoActionsTags.modifyratecap,
        protoActionsTags.modifybase,
        protoActionsTags.modifydecay,
    ],
    'SpeedBonusDivine': [
        protoActionsTags.modifytype,
        protoActionsTags.modifyamount,
        protoActionsTags.modifyratecap,
        protoActionsTags.modifybase,
        protoActionsTags.modifydecay,
    ],
    'MythSelfDestructMundaneAttack': [
        protoActionsTags.damage,
        protoActionsTags.damagebonus,
        protoActionsTags.basedamagecap,
        protoActionsTags.damagearea,
        protoActionsTags.damageflags,
    ],
    'MythSelfDestructRareAttack': [
        protoActionsTags.damage,
        protoActionsTags.damagebonus,
        protoActionsTags.basedamagecap,
        protoActionsTags.damagearea,
        protoActionsTags.damageflags,
    ],
    'MythSelfDestructMythicalAttack': [
        protoActionsTags.damage,
        protoActionsTags.damagebonus,
        protoActionsTags.basedamagecap,
        protoActionsTags.damagearea,
        protoActionsTags.damageflags,
    ],
    'MythSelfDestructDivineAttack': [
        protoActionsTags.damage,
        protoActionsTags.damagebonus,
        protoActionsTags.basedamagecap,
        protoActionsTags.damagearea,
        protoActionsTags.damageflags,
    ],
    'LonghouseSpeedBonus': [
        protoActionsTags.modifytype,
        protoActionsTags.modifyamount,
        protoActionsTags.modifyratecap,
        protoActionsTags.modifybase,
        protoActionsTags.modifydecay,
    ],
    'Attaching': [
        protoActionsTags.rof,
        protoActionsTags.damage,
    ],
    'DelayedTransform': [
        protoActionsTags.modifyduration,
        protoActionsTags.modifyprotoid,
    ],
    'Punt': [
        protoActionsTags.rof,
        protoActionsTags.damage,
        protoActionsTags.maxrange,
        protoActionsTags.active,
    ],
    'Footy': [
        protoActionsTags.rof,
        protoActionsTags.damage,
        protoActionsTags.maxrange,
        protoActionsTags.active,
    ],
    'IncreaseDamageWithLikeUnits': [
        protoActionsTags.maxrange,
        protoActionsTags.modifydamagetype,
        protoActionsTags.modifymultiplier,
        protoActionsTags.modifytargetlimit,
    ],
    'IncreaseSpeedWithLikeUnits': [
        protoActionsTags.maxrange,
        protoActionsTags.modifytype,
        protoActionsTags.modifymultiplier,
        protoActionsTags.modifytargetlimit,
    ],
    'DynamicLOS': [
        protoActionsTags.modifytype,
        protoActionsTags.modifyamount,
        protoActionsTags.modifyratecap,
        protoActionsTags.modifydecay,
    ],
    'ChaosAttack': [
        protoActionsTags.onhiteffect,
        protoActionsTags.rof,
        protoActionsTags.maxrange,
    ],
    'TransfigurationAttack': [
        protoActionsTags.rof,
        protoActionsTags.maxrange,
        protoActionsTags.active,
        protoActionsTags.onhiteffect,
    ],
    'Eat': [
        protoActionsTags.rate,
        protoActionsTags.maxrange,
    ],
    'DwarvenPunt': [
        protoActionsTags.rof,
        protoActionsTags.damage,
        protoActionsTags.maxrange,
    ],
    'BurstHeal': [
        protoActionsTags.rof,
        protoActionsTags.maxrange,
        protoActionsTags.rate,
    ],
    'AutoGatherFood': [protoActionsTags.rate],
}).value
